name: Test

on:
  push:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update rust stable
        run: rustup update stable && rustup default stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
